@echo off

set /p EFILING_DATABASE_USER_NAME=Enter Database User Name:
set /p EFILING_DATABASE_PASSWORD=Enter Database Password:
set /p EFILING_DATABASE_SERVER_NAME=Enter Database Server Name:
set /p EFILING_DATABASE_PORT=Enter Database Port:
set /p EFILING_DATABASE_NAME=Enter Database Name:

setx EFILING_DATABASE_USER_NAME "%EFILING_DATABASE_USER_NAME%" /M
setx EFILING_DATABASE_PASSWORD "%EFILING_DATABASE_PASSWORD%" /M
setx EFILING_DATABASE_SERVER_NAME "%EFILING_DATABASE_SERVER_NAME%" /M
setx EFILING_DATABASE_PORT "%EFILING_DATABASE_PORT%" /M
setx EFILING_DATABASE_NAME "%EFILING_DATABASE_NAME%" /M

echo Environment variables set
pause